### ISSUE TITLE
Error handling problem.

### ISSUE THREAD

**Issue by belkovmv** [mosquito/aiormq#127]
Hello.
Accidentally encountered a hang in the basic_publish() method.
A small example demonstrates this.

```python
import asyncio
import aiormq
import logging


async def test():
    amqp_url = "amqp://user:password@127.0.0.1/vhost"
    connection = await aiormq.connect(amqp_url)
    channel = await connection.channel()

    # Passing the wrong parameter type to basic_publish() body parameter str instead of bytes.
    # Execution hangs on call basic_publish().
    # No exception was thrown.
    # There is no error in the log.
    await channel.basic_publish("123")

    await connection.close()


try:
    logging.basicConfig(level=logging.DEBUG)

    loop = asyncio.get_event_loop()
    loop.run_until_complete(test())
    loop.close()
except Exception as e:
    print("Exception:", e)
```

**Comment by Juhaz** [comment]
this issue is back after b43821bbc5ad987ccb400c9d7b05bf1f9c9b9fd0 and the workaround never fixed the miserable error handling in general. What is swallowing this exception and why? This sort of issue should not be a nightmare to debug that it is.

After adding some debug logging to connection.py:
```
2023-02-01 09:45:56,314:ERROR:aiormq.connection:Unhandled exception in writer
Traceback (most recent call last):
  File "/home/me/aioenv/lib/python3.7/site-packages/aiormq/connection.py", line 633, in __writer
    frame, channel_frame.channel_number,
  File "/home/me/aioenv/lib/python3.7/site-packages/pamqp/frame.py", line 38, in marshal
    return _marshal_content_body_frame(frame_value, channel_id)
  File "/home/me/aioenv/lib/python3.7/site-packages/pamqp/frame.py", line 106, in _marshal_content_body_frame
    return _marshal(constants.FRAME_BODY, channel_id, value.marshal())
  File "/home/me/aioenv/lib/python3.7/site-packages/pamqp/frame.py", line 99, in _marshal
    constants.FRAME_END_CHAR
TypeError: sequence item 1: expected a bytes-like object, str found
2023-02-01 09:45:56,315:DEBUG:aiormq.connection:Writer exited for <Connection: "*SNIP*" at 0x7fec7e50d188>
```

FWIW it's even worse when this happens in a task where it does not block processing - the writer is killed, but the connection/channel does not get closed so receiving messages continues to "work", except you can't ack anything without the writer so everything in some half-functional limbo state.

**Comment by mosquito** [comment]
Looks like you trying to send str in body instead of bytes. I strictly recommend you use mypy for found bad code. Of course the library should check it before sending to writer, I will fix it soon.

**Comment by Juhaz** [comment]
I don't think the library should necessarily check - but it shouldn't suppress errors unless they are being handled and need not be known about. The exception I pasted would have been more than enough to indicate what the problem is, but it's caught somewhere that I can not quite identify, and not re-raised or logged.

Nor should it enter inconsistent state as a result.

**Comment by mosquito** [comment]
You are right, but for a long time I wanted to move frame marshalling to the frame initialization stage, so that the writer would be only writing a stream of bytes into the socket. In #164, I tried to do just that.
